### ISSUE TITLE
Better lookup for URLs inside strings

### ISSUE THREAD

**Issue by zivnevo** [np-guard/cluster-topology-analyzer#353]
Found the following example in `openshift-operator-lifecycle-manager`
```yaml
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: collect-profiles
    namespace: openshift-operator-lifecycle-manager
  spec:
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          spec:
            containers:
            - args:
              - -n
              - openshift-operator-lifecycle-manager
              - --config-mount-path
              - /etc/config
              - --cert-mount-path
              - /var/run/secrets/serving-cert
              - olm-operator-heap-:https://olm-operator-metrics:8443/debug/pprof/heap
              - catalog-operator-heap-:https://catalog-operator-metrics:8443/debug/pprof/heap
```
Both `olm-operator-metrics` and `catalog-operator-metrics` are local service names.
